apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tpmmf8jmk-python 
  janus-idp.io/tekton: tpmmf8jmk-python
  backstage.io/kubernetes-id: tpmmf8jmk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tpmmf8jmk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml